[package]
name = "lucy-dp"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "lucy_dp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quotients-array = { path = "../../data-structure/quotients-array" }
prime-sieve = { path = "../../math/prime-sieve" }