[package]
name = "zalgorithm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
z-algorithm = { path = "../../crates/sequence/z-algorithm" }
itertools = "=0.9.0"
