[package]
name = "formal_power_series"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "formal_power_series"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
numeric_traits = { path = "../../algebra/numeric_traits" }
modint = { path = "../../number_theory/modint/modint" }
static_modint = { path = "../../number_theory/modint/static_modint" }
dynamic_modint = { path = "../../number_theory/modint/dynamic_modint" }
binomial = { path = "../../combinatorics/binomial" }
convolution = { path = "../../convolution/convolution" }
