[package]
name = "tree_contour_range"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "tree_contour_range"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csr_array = { path = "../../data_structure/csr_array" }
graph = { path = "../../graph/graph" }
