[package]
name = "count_spanning_tree_directed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
modint = { path = "../../crates/number-theory/modint" }
count-spanning-tree-directed = { path = "../../crates/graph/count-spanning-tree-directed" }
