[package]
name = "splay-tree"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "splay_tree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebraic = { path = "../../algebraic/algebraic" }
splay-tree-internal = { path = "../../data-structure/splay-tree-internal" }
