[workspace]
members = [
    "crates/algebra/*",
    "crates/data_structure/*",
    "crates/data_structure/union_find/*",
    "crates/misc/*",
    "crates/number_theory/modint/*",

    # "crates/algebraic/*",
    # "crates/algorithm/*",
    # "crates/convolution/*",
    # "crates/data-structure/*",
    # "crates/dp/*",
    # "crates/graph/*",
    # "crates/heuristic/*",
    # "crates/macros/*",
    # "crates/math/*",
    # "crates/polynomial/*",
    # "crates/sequence/*",
    # "crates/string/*",
    # "crates/tree/*",
    # "crates/misc/*",
    # "crates/number-theory/*",

    "verify/library_checker/sample/*",
    "verify/library_checker/number_theory/*",
    "verify/library_checker/data_structure/*",
]

exclude = ["crates/data_structure/union_find"]
