[workspace]
members = [
    "crates/algebraic/*",
    "crates/algorithm/*",
    "crates/convolution/*",
    "crates/data-structure/*",
    "crates/graph/*",
    "crates/macros/*",
    "crates/math/*",
    "crates/polynomial/*",
    "crates/sequence/*",
    "crates/tree/*",
    "verify/*",
]
