[workspace]
members = [
    "crates/algebra/algebraic_structure",
    "crates/algebra/algebraic_traits",
    "crates/algebra/numeric_traits",
    "crates/data_structure/disjoint_sparse_table",
    "crates/data_structure/fenwick_tree/fenwick_tree",
    "crates/data_structure/segment_tree/dual_segment_tree",
    "crates/data_structure/segment_tree/lazy_segment_tree",
    "crates/data_structure/segment_tree/segment_tree",
    "crates/data_structure/union_find/union_find",
    "crates/misc/into_half_open_range",
    "crates/number_theory/modint/dynamic_modint",
    "crates/number_theory/modint/dynamic_modint_64",
    "crates/number_theory/modint/modint",
    "crates/number_theory/modint/modint_mersenne",
    "crates/number_theory/modint/static_modint",
    "verify/library_checker/data_structure/point_add_range_sum",
    "verify/library_checker/data_structure/point_set_range_composite",
    "verify/library_checker/data_structure/range_affine_point_get",
    "verify/library_checker/data_structure/range_affine_range_sum",
    "verify/library_checker/data_structure/staticrmq_dst",
    "verify/library_checker/data_structure/unionfind",
    "verify/library_checker/data_structure/unionfind_with_potential",
    "verify/library_checker/number_theory/sqrt_mod",
    "verify/library_checker/sample/aplusb",
]
