[package]
name = "tree_path_composite_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
graph = { path = "../../crates/graph/graph" }
algebraic = { path = "../../crates/algebraic/algebraic" }
re-rooting-dp = { path = "../../crates/tree/re-rooting-dp" }
modint = { path = "../../crates/number-theory/modint" }
itertools = "=0.9.0"
