[package]
name = "convolution-ntt-friendly"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "convolution_ntt_friendly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { path = "../../number-theory/modint" }
convolution-naive = { path = "../../convolution/convolution-naive" }
