[package]
name = "prime_factorization"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "prime_factorization"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamic_modint_64 = { path = "../modint/dynamic_modint_64" }
numeric_traits = { path = "../../algebra/numeric_traits" }
