[package]
name = "project-selection"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "project_selection"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
max-flow = { path = "../../graph/max-flow" }
