[package]
name = "cartesian_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
cartesian-tree = { path = "../../crates/tree/cartesian-tree" }
itertools = "=0.9.0"
