[package]
name = "staticrmq"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
algebraic = { package = "algebraic", path = "../../crates/algebraic/algebraic" }
disjoint-sparse-table = { package = "disjoint-sparse-table", path = "../../crates/data-structure/disjoint-sparse-table" }
