[package]
name = "vertex_set_path_composite"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
ac-library-rs = { git = "https://github.com/rust-lang-ja/ac-library-rs" }
tree-query = { package = "tree-query", path = "../../crates/data-structure/tree-query" }
graph = { package = "graph", path = "../../crates/graph/graph" }
