[package]
name = "static_rectangle_add_rectangle_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
static-rectangle-add-rectangle-sum = { path = "../../crates/algorithm/static-rectangle-add-rectangle-sum" }
modint = { path = "../../crates/number-theory/modint" }
