[package]
name = "static_top_tree"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "static_top_tree"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csr_array = { path = "../../data_structure/csr_array" }
heavy_light_decomposition = { path = "../../tree/heavy_light_decomposition" }
# graph = { path = "../../graph/graph" }
