[package]
name = "vertex_get_range_contour_add_on_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
algebraic = { path = "../../crates/algebraic/algebraic" }
vertex-get-range-contour-add = { path = "../../crates/data-structure/vertex-get-range-contour-add" }
