[package]
name = "static_modint"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "static_modint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { path = "../modint" }
algebraic_structure = { path = "../../../algebra/algebraic_structure" }
algebraic_traits = { path = "../../../algebra/algebraic_traits" }
numeric_traits = { path = "../../../algebra/numeric_traits" }
