[package]
name = "static_modint"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "static_modint"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { path = "../modint" }
numeric_traits = { path = "../../../algebra/numeric_traits" }
