[package]
name = "wildcard_pattern_matching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
itertools = "=0.9.0"
wildcard-pattern-matching = { path = "../../crates/string/wildcard-pattern-matching" }