[package]
name = "dynamic_sequence_range_affine_range_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
algebraic_structure = { path = "../../../../crates/algebra/algebraic_structure" }
static_modint = { path = "../../../../crates/number_theory/modint/static_modint" }
splay_tree = { path = "../../../../crates/data_structure/splay_tree" }
