[package]
name = "simulated-annealing-scheduler"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "simulated_annealing_scheduler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = { path = "../../heuristic/timer" }
random = { path = "../../misc/random" }
