[package]
name = "inv_of_formal_power_series_not_ntt_friendly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
dynamic_modint = { path = "../../../../crates/number_theory/modint/dynamic_modint" }
formal_power_series = { path = "../../../../crates/polynomial/formal_power_series" }
