[package]
name = "matrix"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
publish = false

[lib]
name = "matrix"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
