[package]
name = "range-union-find"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "range_union_find"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random = { path = "../../misc/random" }
modint61 = { path = "../../math/modint61" }
segment-tree = { path = "../../data-structure/segment-tree" }
algebraic = { path = "../../algebraic/algebraic" }
