[package]
name = "vertex-add-range-contour-sum"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "vertex_add_range_contour_sum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = { path = "../../graph/graph" }
algebraic = { path = "../../algebraic/algebraic" }
segment-tree = { path = "../../data-structure/segment-tree" }
range-contour-query = { path = "../../data-structure/range-contour-query" }
