[package]
name = "sum_of_multiplicative_function"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
min_25-sieve = { path = "../../crates/math/min_25-sieve" }
lucy-dp = { path = "../../crates/math/lucy-dp" }
quotients-array = { path = "../../crates/data-structure/quotients-array" }
proconio = { version = "=0.3.6", features = ["derive"] }
modint = { path = "../../crates/number-theory/modint" }
