[package]
name = "biconnected_components"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
graph = { path = "../../crates/graph/graph" }
extended-block-cut-tree = { path = "../../crates/graph/extended-block-cut-tree" }
itertools = "=0.9.0"
