[package]
name = "two_edge_connected_components_lc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
graph = { path = "../../../../crates/graph/graph" }
two_edge_connected_components = { path = "../../../../crates/graph/two_edge_connected_components" }
