[package]
name = "rolling-hash"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
publish = false

[lib]
name = "rolling_hash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random = { path = "../../misc/random" }
nimber = { path = "../../math/nimber" }
modint61 = { path = "../../math/modint61" }
