[package]
name = "heavy-light-decomposition-noya2"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "heavy_light_decomposition_noya2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = { package = "graph", path = "../../graph/graph" }
