[package]
name = "dynamic_graph_vertex_add_component_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
offline-dynamic-connectivity = { path = "../../crates/algorithm/offline-dynamic-connectivity" }
rollback-union-find-component-sum = { path = "../../crates/data-structure/rollback-union-find-component-sum" }
algebraic = { path = "../../crates/algebraic/algebraic" }