[package]
name = "vertex-get-range-contour-add"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "vertex_get_range_contour_add"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = { path = "../../graph/graph" }
algebraic = { path = "../../algebraic/algebraic" }
dual-segment-tree = { path = "../../data-structure/dual-segment-tree" }
range-contour-query = { path = "../../data-structure/range-contour-query" }
