[package]
name = "vertex_add_path_sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
segment-tree = { path = "../../crates/data-structure/segment-tree" }
graph = { path = "../../crates/graph/graph" }
algebraic = { path = "../../crates/algebraic/algebraic" }
heavy-light-decomposition = { path = "../../crates/tree/heavy-light-decomposition" }
