[package]
name = "point_set_range_frequency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
wavelet_matrix = { path = "../../../../crates/data_structure/wavelet_matrix" }
fenwick_tree = { path = "../../../../crates/data_structure/fenwick_tree/fenwick_tree" }
algebraic_structure = { path = "../../../../crates/algebra/algebraic_structure" }
