[package]
name = "unionfind_with_potential_non_commutative_group"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
potentialized-union-find = { path = "../../crates/data-structure/potentialized-union-find" }
modint = { path = "../../crates/number-theory/modint" }
