[package]
name = "vertex_set_path_composite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
heavy_light_decomposition = { path = "../../../../crates/tree/heavy_light_decomposition" }
algebraic_structure = { path = "../../../../crates/algebra/algebraic_structure" }
algebraic_traits = { path = "../../../../crates/algebra/algebraic_traits" }
segment_tree = { path = "../../../../crates/data_structure/segment_tree/segment_tree" }
static_modint = { path = "../../../../crates/number_theory/modint/static_modint" }
