[package]
name = "yuki1014"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
graph = { path = "../../crates/graph/graph" }
range-edge-graph = { path = "../../crates/graph/range-edge-graph" }
chminmax = { path = "../../crates/macros/chminmax" }