[package]
name = "unionfind_with_potential_non_commutative_group"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
union_find = { path = "../../../../crates/data_structure/union_find/union_find" }
algebraic_structure = { path = "../../../../crates/algebra/algebraic_structure" }
algebraic_traits = { path = "../../../../crates/algebra/algebraic_traits" }
static_modint = { path = "../../../../crates/number_theory/modint/static_modint" }
