[package]
name = "segment-tree-on-wavelet-matrix"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "segment_tree_on_wavelet_matrix"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
segment-tree = { path = "../segment-tree" }
algebraic = { path = "../../algebraic/algebraic" }
