[package]
name = "static-range-inversions-query"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "static_range_inversions_query"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
div = { package = "div", path = "../../math/div" }
