[package]
name = "range_reverse_range_sum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
algebraic = { path = "../../crates/algebraic/algebraic" }
splay-tree = { path = "../../crates/data-structure/splay-tree" }
