[package]
name = "yuki1269"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
trie = { path = "../../crates/string/trie" }
modint = { path = "../../crates/number-theory/modint" }
