[package]
name = "persistent-union-find"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "persistent_union_find"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
persistent-array = { path = "../../data-structure/persistent-array" }
