[package]
name = "shift_of_sampling_points_of_polynomial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "=0.9.0"
modint = { path = "../../crates/number-theory/modint" }
formal-power-series = { path = "../../crates/polynomial/formal-power-series" }
shift-of-sampling-points = { path = "../../crates/polynomial/shift-of-sampling-points" }
proconio = { version = "=0.3.6", features = ["derive"] }
