[package]
name = "frequency_table_of_tree_distance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
centroid_decomposition = { path = "../../../../crates/tree/centroid_decomposition" }
convolution = { path = "../../../../crates/convolution/convolution" }
graph = { path = "../../../../crates/graph/graph" }
static_modint = { path = "../../../../crates/number_theory/modint/static_modint" }
