[package]
name = "enumerate_quotients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quotients = { path = "../../crates/number-theory/quotients" }
proconio = { version = "=0.3.6", features = ["derive"] }
itertools = "0.10"