[package]
name = "stern_brocot_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
rational = { path = "../../crates/algebraic/rational" }
stern-brocot-tree = { path = "../../crates/math/stern-brocot-tree" }