[package]
name = "max-flow-lower-bound"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
publish = false

[lib]
name = "max_flow_lower_bound"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
max-flow = { path = "../../graph/max-flow" }
