[package]
name = "union_find"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "union_find"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebraic_traits = { path = "../../../algebra/algebraic_traits" }
algebraic_structure = { path = "../../../algebra/algebraic_structure" }
