[package]
name = "static_range_inversions_query_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
static-range-inversions-query = { path = "../../crates/data-structure/static-range-inversions-query" }
