[package]
name = "enumerate_primes_ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
linear_sieve = { path = "../../../../crates/number_theory/linear_sieve" }
