[package]
name = "disjoint-sparse-table"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "disjoint_sparse_table"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebraic = { package = "algebraic", path = "../../algebraic/algebraic" }
