[package]
name = "algebraic_structure"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "algebraic_structure"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebraic_traits = { path = "../algebraic_traits" }
primitive_number = { path = "../primitive_number" }
modint = { path = "../../number-theory/modint" }
