[package]
name = "zalgorithm_rolling_hash"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
rolling-hash = { path = "../../crates/string/rolling-hash" }
modint61 = { path = "../../crates/math/modint61" }
itertools = "=0.9.0"
