[package]
name = "suffix-array"
version = "0.1.0"
edition = "2018"
license = "CC0-1.0"
publish = false

[lib]
name = "suffix_array"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disjoint-sparse-table = { path = "../../data-structure/disjoint-sparse-table" }
algebraic = { path = "../../algebraic/algebraic" }
