[package]
name = "associative_array_bt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
binary_trie = { path = "../../../../crates/data_structure/binary_trie" }
