[package]
name = "point_set_tree_path_composite_sum_fixed_root"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
graph = { path = "../../crates/graph/graph" }
dynamic-tree-dp = { path = "../../crates/tree/dynamic-tree-dp" }
modint = { path = "../../crates/number-theory/modint" }
