[package]
name = "shift-of-sampling-points"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "shift_of_sampling_points"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { path = "../../number-theory/modint" }
formal-power-series = { path = "../../polynomial/formal-power-series" }
