[package]
name = "formal-power-series"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"
publish = false

[lib]
name = "formal_power_series"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modint = { path = "../../number-theory/modint" }
convolution-ntt-friendly = { path = "../../convolution/convolution-ntt-friendly" }
convolution-arbitrary-mod = { path = "../../convolution/convolution-arbitrary-mod" }
