[package]
name = "unionfind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "=0.5.0", features = ["derive"] }
union_find = { path = "../../../../crates/data_structure/union_find/union_find" }
